[package]
name = "miratope"
version = "0.1.0"
authors = ["Violeta Hernández <vi.hdz.p@gmail.com>", "Grayson Burton <ocornoc@protonmail.com>"]
edition = "2018"

[dependencies]
bevy = "0.4.0"
rand = "0.8.3"
serde = {version = "1.0.123", features = ["derive"]}
ron = "0.6.4"
nalgebra = {version = "0.24.1", features = ["serde-serialize"]}
# bevy_egui = "0.2.0"

[profile.release]
lto = "thin"
incremental = true
