[workspace]
members = ["miratope-core", "miratope-lang", "vec-like"]

[package]
name = "miratope"
description = "A polytope renderer and builder."
license = "MIT"
version = "0.1.0"
repository = "https://github.com/OfficialURL/miratope-rs"
keywords = ["polytope", "dimension", "geometry"]
authors = [
    "Violeta Hernández <vi.hdz.p@gmail.com>",
    "Grayson Burton <ocornoc@protonmail.com>",
    "Roman Salinas <ultraroman01@gmail.com>"
]
edition = "2018"

[dependencies]
miratope-core = { path = "miratope-core" }
miratope-lang = { path = "miratope-lang" }
vec-like = { path = "vec-like" }
approx = "0.5"
directories = "3.0"
lyon = "0.17"
rfd = "0.4"
ron = "0.6"
serde = { version = "1.0", features = ["derive"] }
strum = "0.21"
strum_macros = "0.21"
webbrowser = "0.5"

# Use latest version of Bevy (might cause breakage!)
[dependencies.bevy]
git = "https://github.com/bevyengine/bevy"
branch = "main"
default-features = false
features = [
    "bevy_gltf",
    "bevy_winit",
    "bevy_wgpu",
    "render",
    "bevy_dynamic_plugin",
    "hdr",
    "x11"
]

# Bevy egui integration with this latest version.
[dependencies.bevy_egui]
git = "https://github.com/OfficialURL/bevy_egui/"
branch = "bevy-main"

[dependencies.egui]
version = "0.14.2"
default-features = false
features = ["multi_threaded"]

[profile.release]
lto = "thin"
incremental = true
