[package]
name = "miratope"
version = "0.1.0"
authors = ["Violeta Hernández <vi.hdz.p@gmail.com>", "Grayson Burton <ocornoc@protonmail.com>"]
edition = "2018"

[dependencies]
approx = "0.4"
bevy = "0.4"
bevy_egui = "0.3"
derive_deref = "1.1"
dyn-clone = "1.0"
factorial = "0.2"
gcd = "2.0"
itertools = "0.10"
nalgebra = {version = "0.26", features = ["serde-serialize"]}
petgraph = "0.5"
rand = "0.8"
regex = "1.4"
ron = "0.6"
scapegoat = "1.0"
serde = {version = "1.0", features = ["derive"]}
xml-rs = "0.8"
zip = "0.5"

[profile.release]
lto = "thin"
incremental = true