[package]
name = "miratope"
description = "A polytope renderer and builder."
license = "MIT"
version = "0.1.0"
repository = "https://github.com/OfficialURL/miratope-rs"
keywords = ["polytope", "dimension", "geometry"]
authors = ["Violeta Hernández <vi.hdz.p@gmail.com>", "Grayson Burton <ocornoc@protonmail.com>", "Roman Salinas <ultraroman01@gmail.com>"]
edition = "2018"

[dependencies]
approx = "0.4"
dyn-clone = "1.0"
factorial = "0.2"
float-ord = "0.3"
gcd = "2.0"
itertools = "0.10"
lyon = "0.17"
nalgebra = {version = "0.26", features = ["serde-serialize", "rand"]}
petgraph = "0.5"
rand = "0.8"
rfd = "0.3"
ron = "0.6"
scapegoat = "1.0"
serde = {version = "1.0", features = ["derive"]}
strum = "0.20"
strum_macros = "0.20"
webbrowser = "0.5"
xml-rs = "0.8"
zip = "0.5"

# Use latest version of Bevy (might cause breakage!)
[dependencies.bevy_egui]
git = "https://github.com/jakobhellermann/bevy_egui"
branch = "bevy-main"

[dependencies.bevy]
git = "https://github.com/bevyengine/bevy"
branch = "main"

# We need to disable audio for file dialogs to work... for some reason.
default-features = false
features = ["bevy_gltf", "bevy_winit", "bevy_wgpu", "render", "bevy_dynamic_plugin", "hdr", "x11"]

[patch.crates-io]
# Patches egui issue #404.
egui = { git = "https://github.com/emilk/egui" }

# Fixes winit issue #1779.
winit = { git = 'https://github.com/OfficialURL/winit' }

[profile.release]
lto = "thin"
incremental = true