[package]
name = "miratope"
description = "A polytope renderer and builder."
license = "MIT"
version = "0.1.0"
repository = "https://github.com/OfficialURL/miratope-rs"
keywords = ["polytope", "dimension", "geometry"]
authors = ["Violeta Hernández <vi.hdz.p@gmail.com>", "Grayson Burton <ocornoc@protonmail.com>", "Roman Salinas <ultraroman01@gmail.com>"]
edition = "2018"

[dependencies]
approx = "0.4"
bevy_egui = "0.4"
dyn-clone = "1.0"
factorial = "0.2"
float-ord = "0.3"
gcd = "2.0"
itertools = "0.10"
lyon = "0.17"
nalgebra = {version = "0.26", features = ["serde-serialize", "rand"]}
petgraph = "0.5"
rand = "0.8"
rfd = "0.3"
ron = "0.6"
scapegoat = "1.0"
serde = {version = "1.0", features = ["derive"]}
strum = "0.20"
strum_macros = "0.20"
webbrowser = "0.5"
xml-rs = "0.8"
zip = "0.5"

[dependencies.bevy]
version = "0.5"
default-features = false
features = ["bevy_gltf", "bevy_winit", "bevy_wgpu", "render", "bevy_dynamic_plugin", "hdr", "x11"]

[patch.crates-io]
# Bumps egui to 0.12.0.
bevy_egui = { git = "https://github.com/ndarilek/bevy_egui", branch = "main" }

# Fixes winit issue #1779.
winit = { git = 'https://github.com/OfficialURL/winit', rev = '078b9719cc3ba06630291d5bc05c90787bd84c4f' }

[profile.release]
lto = "thin"
incremental = true