name: Rust Build

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false 
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: sudo apt-get update; sudo apt-get install --no-install-recommends pkg-config libx11-dev libasound2-dev libudev-dev
        if: runner.os == 'linux'
      
      - name: Build & run tests
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo fmt -- --check && cargo clippy -- -Dwarnings && cargo test
