name: Rust Build

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false 
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      RUST_BACKTRACE: 1

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: sudo apt-get update; sudo apt-get install --no-install-recommends pkg-config libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libx11-dev libasound2-dev libudev-dev
        if: runner.os == 'linux'
      
      - name: Build & run tests
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo fmt -- --check && cargo clippy -- -Dwarnings && cargo --release test
